language: php

php:
  - 7.0
  - 7.1
  - 7.2

install:
  - travis_retry composer update

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover coverage.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml

matrix:
    allow_failures:
        - php: 7.1
